version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-crawler_legal}
      POSTGRES_USER: ${POSTGRES_USER:-crawler_admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-SecurePassword123!}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-crawler_admin}"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER:-mongo_admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD:-SecureMongoPass456!}
      MONGO_INITDB_DATABASE: ${MONGODB_DB:-judicial_documents}
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD:-SecureRedisPass789!}
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-rabbitmq_admin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-SecureRabbitPass012!}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST:-/crawler}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  opensearch:
    image: opensearchproject/opensearch:2.11.0
    environment:
      discovery.type: single-node
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: ${OPENSEARCH_PASSWORD:-SecureSearchPass345!}
      DISABLE_SECURITY_PLUGIN: "true"
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    ports:
      - "9200:9200"

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    command: streamlit run dashboard/app.py
    env_file: .env
    ports:
      - "8501:8501"
    depends_on:
      - postgres
      - mongodb
      - redis
    volumes:
      - ./dashboard:/app/dashboard
      - ./src:/app/src

volumes:
  postgres_data:
  mongodb_data:
  redis_data:
  rabbitmq_data:
  opensearch_data:
